### ISSUE TITLE
initialPage not working 

### ISSUE THREAD

**Issue by jmn** [Luehang/react-native-gallery-swiper#11]
I can't seem to get the initialPage prop working. The gallery always starts at index 0, I tried setting the initialNumToRender to the same number but it didn't help. I've tested on Android only.

**Comment by Luehang** [comment]
Hi.  Can I see an example of your codes?

**Comment by Luehang** [comment]
The `initialNumToRender` starts at index 1.

**Comment by jmn** [comment]
Sorry, I tried setting the initialNumToRender at index +1 but still initialPage didn't work.

**Comment by Luehang** [comment]
Hi, sorry about the late reply.  I don't think the `initialNumToRender` prop is dynamic.  `react-native-gallery-swiper` uses `FlatList` underneath the hood.  It sounds like you are trying to dynamically change it.  You can use this other module for initial page rendering.  [`react-native-smart-gallery`](https://github.com/Luehang/react-native-smart-gallery).
