### ISSUE TITLE
how to chnage images array with state

### ISSUE THREAD

**Issue by rezapiryghadim** [Luehang/react-native-gallery-swiper#12]
I want change images array of gallery after a while

 i tried i read images array from my state's that's changing but slider fixed in first image array .

how can i reset gallery images ?

my code 

`
<GallerySwiper
                                                           refPage={(component) => (this.gallerySwiper = component)}
                                                           style={{backgroundColor : 'transparent' , flex:1 , height:200 , width: '100%'}}
                                                           images={this.state.showcase[this.state.galleryType]}
                                                           initialNumToRender={2}
                                                           resizeMode={'cover'}
                                                           sensitiveScroll={false}
                                                           enableScale={false}
                                                           enableTranslate={false}
                                                           enableResistance={false}
                                                       /> 
`

**Comment by Luehang** [comment]
Hi,

For iOS, you can dynamically change the index for `initialPage` prop.  For a better experience on iOS and Android, you can use the methods provided or another alternative is to use the `refPage` prop.  Read the documentation for further instructions.
