### ISSUE TITLE
Serious performance problem

### ISSUE THREAD

**Issue by Frekansapp** [Luehang/react-native-gallery-swiper#13]
After 20 image component getting very poor performance. Can you try https://github.com/Flipkart/recyclerlistview instead of using Flatlist.

**Comment by Luehang** [comment]
Hi @Frekansapp,

This was solved a long time ago.  I decided to create another gallery that uses minimal rendering at one time and the initial index can be placed anywhere.  It's recommended for very large lists (100s to 1000s). Visit [react-native-smart-gallery](https://github.com/Luehang/react-native-smart-gallery).

**Comment by Luehang** [comment]
I will also look at `recyclerlistview` to see if the performance is good and if it can fit with the gallery.    It will have to be better than [`react-native-smart-gallery`](https://github.com/Luehang/react-native-smart-gallery)'s scroller.

**Comment by Frekansapp** [comment]
@Luehang thank you for quick answer. recyclerlistview realy performant solution but I have a problem I encountered. https://github.com/Flipkart/recyclerlistview/issues/333 if this issue not affect your use-case you can try it.

**Comment by abrenoch** [comment]
@Luehang 

What is the difference between `react-native-smart-gallery` and this one? I'm trying out this component and am finding that the behavior when swiping between pages isn't all that great - Pages frequently get stuck or fail to snap to the selected page.
