### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Appdevsoft** [Luehang/react-native-gallery-swiper#15]
Used Latest version, but not worked if image array contains more than 10 or 20 or 50. Totally time waste. 

1. can't swipe left or right
2.  initialPage not loaded correctly

**Comment by Luehang** [comment]
Hi,

It works fine on both iOS and Android.  Which OS version did you use it on?

**Comment by Luehang** [comment]
This issues has been close because it is not causing that current issue when being tested both on iOS and Android.  Please fill out the entire formatted form for the issue for a thorough detail of the occurring issue.
