### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by philipphecht** [Luehang/react-native-gallery-swiper#19]
**To Do First**
- [ ] Take a look in the [README](https://github.com/Luehang/react-native-gallery-swiper/blob/master/README.md)
- [ ] Take a look in the [docs](https://luehangs.site/lue_hang/projects/react-native-gallery-swiper)

**Ask your Question**
Do the plugin supports Orientation in Landscape and Portrait? I tried it when i change from Portrait to Lanscape the gallery don't work correctly?

**Tags**

**Comment by MaximusBaton** [comment]
@philipphecht did you find an alternative to this lib? 

I tried nearly 5 of available and non was working smoothly as this does. BUT this one has problems with orientation.

**Comment by philipphecht** [comment]
This one works but it is very old: https://github.com/ldn0x7dc/react-native-gallery

**Comment by Luehang** [comment]
Some galleries are locked in one orientation, and orientation support re-renders (unnecessary) the gallery a lot which causes the slowness in most galleries.  It will be an option in the future and it will be optimized.

**Comment by Luehang** [comment]
Hey guys,

There has been a new update that solves the orientation changes issue while sacrificing little performance.  Please update package to version `^1.23.0`.

If you like [`react-native-gallery-swiper`](https://github.com/Luehang/react-native-gallery-swiper), please be sure to give it a star at [GitHub](https://github.com/Luehang/react-native-gallery-swiper). Thanks.

## :gem: Update

Type in the following to the command line to update.

```ssh
$ npm install --save react-native-gallery-swiper@1.23.0
```

or

```ssh
$ yarn add react-native-gallery-swiper@1.23.0
```
