### ISSUE TITLE
[BUG] initialPage not working

### ISSUE THREAD

**Issue by KestasVenslauskas** [Luehang/react-native-gallery-swiper#26]
- [x] Did you try latest release? 
YES
- [x] Did you look for existing matching issues?
YES

**Software Package Version:1.23.1**

**Describe the bug**
When setting 'initialPage' prop component just hangs. If you have like 3-4 images thats ok. But in my case I have 20+ images and if I set initialPage > 5 it hangs.

**To Reproduce**
1. Add many images
2. Set initialPage prop to 10
3. See error

**Expected behavior**
Expected image should be shown.

**Additional context**
Happens on iOS & Android. Not platform related.

**Comment by Luehang** [comment]
Hi,

Have you tried changing the `initialNumToRender` prop?  Depending on your initial page index,  `initialNumToRender` will have to be equal to or greater than.

Props | Description | Type | Default
------ | ------ | ------ | ------
`initialNumToRender` | How many items to render in the initial batch. **Version \*1.3.0 update**. | `number` | `3`
