### ISSUE TITLE
How to persist zoom state

### ISSUE THREAD

**Issue by AlkanV** [Luehang/react-native-gallery-swiper#27]
Hello,
Firstly, thank you for this package. It is working like a charm. 

But i have a little problem with it. When i zoom an image, after releasing my fingers, zoom state returns to initial one. Which means the image i zoomed, is not stay zoomed. Is there any way to solve this problem?

**Comment by ngocht143** [comment]
i faced with same problem @Luehang, please check it, thanks

**Comment by AlkanV** [comment]
@ngocht143 i changed the package and start using react-native-image-zoom-viewer it works seamlessly good.

**Comment by ngocht143** [comment]
@AlkanV can you share what you did with react-native-image-zoom-viewer?

**Comment by AlkanV** [comment]
What do you mean by that? I downloaded package (i.e yarn add) then i used it as instructions says.

**Comment by ngocht143** [comment]
I used the props `imageComponent` but the react-native-image-zoom-viewer use an array of images, so i dont know how to pass each image to get zoomable

**Comment by Luehang** [comment]
Hey guys,

Can I get an example code that was used?

**Comment by ngocht143** [comment]
@Luehang this is my code:
`<SafeAreaView style={{flex: 1, justifyContent: 'center'}}>
                <Gallery
                    refPage={(component) => (this.gallerySwiper = component)}
                    style={{flex: 1, justifyContent: 'center'}}
                    images={this.state.listImage}
                    onSwipeUpReleased={this.onClose}
                    onSwipeDownReleased={this.onClose}
                    sensitiveScroll={false}
                    enableScale
                />
            </SafeAreaView>`

and my list images: `[{"source":{"uri":"https://img.philkotse.com/crop/272x177/2020/02/10/20200210151426-7193.jpg"}},{"source":{"uri":"https://img.philkotse.com/crop/272x177/2020/02/10/20200210151446-48d2.jpg"}}]`

**Comment by Luehang** [comment]
Hi,

This actually isn't a bug.  Under the hood, it is using `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`.

# :books: Props

Props | Description | Type | Default
------ | ------ | ------ | ------
`maxScale` | Max zoom (view transformer). **Version \*1.17.0 update**. | `number` | `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`

To zoom for this tiny image, set the prop `maxScale` to `> 1`.

**Comment by Luehang** [comment]
If you like [`react-native-gallery-swiper`](https://github.com/Luehang/react-native-gallery-swiper), please be sure to give it a star at [GitHub](https://github.com/Luehang/react-native-gallery-swiper). Thanks.

**Comment by ngocht143** [comment]
Hello @Luehang, i still get issue with zoomable feature: When i use FastImage instead of Image in `imageComponent`, then i zoom an image, after releasing my fingers, zoom state returns to initial one. Which means the image i zoomed, is not stay zoomed. This is my code:
`maxScale={20}
  imageComponent={(imageProps, imageDimensions, index) => {
                        return (
                            <View style={{ flex: 1, justifyContent: 'center' }}>
                                <FastImage
                                    source={{ uri: "https://img.philkotse.com/2020/02/10/20200210151426-7193.jpg"}}
                                    style={{width: Configs.deviceWidth,
        height: Configs.deviceWidth / 1.33}} />
                            </View>
                        )
                    }}`

**Comment by thame** [comment]
Having the same issue using any imageComponent other than <Image />

**Comment by Luehang** [comment]
Hi,

Have you guys trying adding all the props from the parameter `imageProps`?

Example

```javascript
<FastImage
    {...imageProps}
/>
```

Let me know if that works.

**Comment by ngocht143** [comment]
@Luehang I tried to add `{...imageProps}` but it still doesn't work (double touch not work, zoomable by fingers but zoom state returns to initial one after release.

**Comment by skizzo** [comment]
Did anybody manage to solve this?
