### ISSUE TITLE
How can i set resizeMode of single image of the Gallery

### ISSUE THREAD

**Issue by pierol** [Luehang/react-native-gallery-swiper#3]
Hi, thank you in advance for your good work and for sharing this wonderful package. I'm using it in a React Native/Expo project where i have a ListView od News. With your package i  can attached to a news more than one pic. My  question is how can i set the resizeMode of the single image so that it cover all the view of the GallerySwipper component.

**Comment by Luehang** [comment]
Hi,

You can use the `imageComponent` prop for a custom image.  An example is also given.  Please give a star for this package if you like it!  Thanks in advance!

Props | Description | Type | Default
------ | ------ | ------ | ------
`imageComponent` | Custom function to render your images. `(imageProps: { imageLoaded: Boolean, source: object, image: object, style: Array<object>, resizeMode: string, capInsets: object, onLoadStart: Function, onLoad: Function, ...extras }, imageDimensions: {width: number, height: number}, index: number) => React.Element` **index params included in Version \*1.3.1 update** | `Function` | `<Image/>` component

```javascript
import GallerySwiper from "react-native-gallery-swiper";

//...
render() {
    return (
        <GallerySwiper
            style={{ flex: 1, backgroundColor: "black" }}
            images={[
                { source: { uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-women-beauty-40901.jpg" } },
                { uri: "https://luehangs.site/pic-chat-app-images/animals-avian-beach-760984.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { URI: "https://luehangs.site/pic-chat-app-images/beautiful-blond-fishnet-stockings-48134.jpg" },
                { url: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-woman-beauty-9763.jpg" },
                { URL: "https://luehangs.site/pic-chat-app-images/attractive-balance-beautiful-186263.jpg" },
            ]}
            imageComponent={(imageProps) => {
               return (
                   <Image
                        {...imageProps}
                        resizeMode="cover"
                   />
               );
            }}
        />
    );
}
//...
```

From,

Lue Hang
