### ISSUE TITLE
[BUG] source in imageProps is undefined

### ISSUE THREAD

**Issue by fattomhk** [Luehang/react-native-gallery-swiper#33]
**To Do First**
- [ Y ] Did you try latest release?
- [ Y ] Did you look for existing matching issues?

**Software Package Version:**
"react-native": "0.61.5",
"react-native-gallery-swiper": "^1.24.1",

**Describe the bug**
Cannot load image at the beginning, the I add imageComponent for debug.
The source in imageProps is undefined.

**To Reproduce**
```
import React, { PureComponent } from 'react';
import GallerySwiper from 'react-native-gallery-swiper';
import {Image} from 'react-native'

const data = Array(1000).fill({uri: 'https://picsum.photos/1920/1080'});

class ImageCarousel extends PureComponent {
	render() {
		return (
			<GallerySwiper
                style={this.props.style}
                enableResistance={false}
                resistantStrHorizontal={0}
                imageComponent={(
                    imageProps, imageDimensions , index
                )=>{
                    const { imageLoaded, source, image, style, resizeMode, capInsets, onLoadStart, onLoad, ...extras } = imageProps;
                    // const {width, height} = imageDimensions;
                    if(!source) {
                        imageProps.source = imageProps.image;
                    }
                    console.log(imageProps);
                    return <Image {...imageProps}/>
                }}
				images={data}
			/>
		);
	}
}

export default ImageCarousel;
```

**Expected behavior**
source exists.

**Comment by Luehang** [comment]
Hi,

Sorry about the late reply.  This was just tested and it seems to be working with no bugs. The current version used for testing this is `^1.25.2`.  Please check out the example project if you are looking for an example that can be customized without all the other custom codes.

**Comment by fattomhk** [comment]
Yes, it is fixed after upgrading to latest version
