### ISSUE TITLE
[BUG] initialPage not setting correctly

### ISSUE THREAD

**Issue by baijii** [Luehang/react-native-gallery-swiper#37]
**To Do First**
- [x] Did you try latest release?
- [x] Did you look for existing matching issues?

**Software Package Version:**
1.25.2

**Describe the bug**
As I set the `initialPage` prop to greater 0, the first image is still be displayed. The current page is displayed as expected in the footer component.

My Test Data:
```
  const images = [
    { source: { uri: 'https://picsum.photos/300/200' } },
    { source: { uri: 'https://picsum.photos/400/100' } }
  ]
```

My Gallery View:
```
  <View style={styles.container}>
      <Header />

      <GallerySwiper
        initialPage={initialIndex}
        images={images}
      />

      <Footer
        renderPageFooter={(image, index) => {
          const page = index + 1
          const total = images.length
          return (
            <View>
              <Text>
                {`${page} / ${total}`}
              </Text>
            </View>
          )
        }}
        images={images}
        galleryIndex={currentIndex}
      />
  </View>
```

**To Reproduce**
1. Add Gallery with 2 images and initialPage of 1
2. The first image is displayed, while the pager says `2 / 2`

**Expected behavior**
The second image is displayed

**Version (please complete the following information):**
 - Device: iPhone8 Simulator
 - iOS: 13
 - react-native: 0.61.5
 - react: 16.9.0

Maybe I'm doing something stupidly wrong. Thanks in advance!

**Comment by ngocht143** [comment]
In my case, i use method `scrollToPage` to jump to expected image

**Comment by pburdynski** [comment]
@ngocht143 could you show how you do it?

**Comment by ngocht143** [comment]
You should declare a`refPage` (in my case is 'gallerySwiper'), then call it when you have the image's position you want as: 
`this.gallerySwiper.scrollToPage(currentPosition - 1, false)`

**Comment by pburdynski** [comment]
Does it work for you if target position is above initialNumToRender? By using both initialPage and scrollToPage I will be taken to the last item rendered, so the only way to make it work is to set initialNumToRender = initialPage+1, which completely defeats purpose of initialNumToRender (which is extremely powerful for large lists).
I've read documentation of flatlist (on which this lib is based) and it suggest that by using initialScrollIndex property you don't render items that are before this index. However, initialScrollIndex is not used in gallerySwiper (scrollToOffset is). I think this is the reason of the bug i'm experiencing.

**Comment by baijii** [comment]
Thank you @ngocht143 , haven't thought of `scrollToPage`.  I got it working. It was still work to be compatible with hooks. 
In my case, it would only work if the second `animated` param is set to true. Don't know why, but it works for me now.

Here's my solution (in parts) for maybe someone else is struggeling:
```
const [initialIndex, setInitialIndex] = useState(0)
const [gallerySwiper, setGallerySwiper] = useState(null)

// also some effect for setting the initialIndex

useEffect(() => {
    if (gallerySwiper) {
      gallerySwiper.scrollToPage(initialIndex, true)
    }
}, [gallerySwiper])

return (
    <GallerySwiper
        refPage={(e) => setGallerySwiper(e)}
        initialPage={initialIndex}
    />
)
```
