### ISSUE TITLE
[BUG] initialPage greater than initialNumToRender

### ISSUE THREAD

**Issue by LorhanSohaky** [Luehang/react-native-gallery-swiper#41]
**To Do First**
- [X] Did you try latest release?
- [X] Did you look for existing matching issues?

**Software Package Version:**
"react-native-gallery-swiper": "^1.25.2"

**Describe the bug**

When I set a `initialPage` greater than`initialNumToRender` the current page is the number in `initialNumToRender`.

**To Reproduce**
[![Edit brave-frost-mjdj1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-frost-mjdj1?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
When i set a `initialPage` its go to the correct page.

**Version (please complete the following information):**
 - react-native: `"react-native": "^0.55.4"`
 - react: `"react": "16.3.1"`

**Additional context**
- Using `"react-native-web": "^0.9.0"`
- My gallery has at least 200 photos
- Photos are between 4MB and 9MB in size

**Comment by Luehang** [comment]
Hi,

You have to set the `initialNumToRender` so it's greater than or equal to `initialPage` if you want to go further to the correct page.  This package uses the underlying react-native `FlatList` and that is normal behavior for optimization.

**Comment by comartekdev** [comment]
I tried your way but it was quite delay
