### ISSUE TITLE
[FEATURE REQUEST] Missing TypeScript definitions

### ISSUE THREAD

**Issue by alessiocancian** [Luehang/react-native-gallery-swiper#45]
Using this library with TypeScript gives this error: 

> Could not find a declaration file for module 'react-native-gallery-swiper'. '/Users/alessiocancian/Desktop/foodlist-upgrade/node_modules/react-native-gallery-swiper/src/index.js' implicitly has an 'any' type.
Try `npm install @types/react-native-gallery-swiper` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-gallery-swiper';`

Would be nice to add a `index.d.ts` file to the project to expose the types for TypeScript compiler and linter.

I'll try to make a Pull Request with the definitions in the next days...

**Comment by alessiocancian** [comment]
@Luehang

**Comment by Luehang** [comment]
Thanks for contributing.
