### ISSUE TITLE
No /src/ folder when installing through Yarn

### ISSUE THREAD

**Issue by jamesether** [Luehang/react-native-gallery-swiper#5]
Hey,

Thank you for the library, it seems to be working great.

In one of the recent updates it appears the `src` folder has disappeared when installing through Yarn. Grabbing it from the repo and putting it in the `node_modules/react-native-gallery-swiper` directory fixes the issue.

Thanks!

**Comment by Luehang** [comment]
Hi,

Thanks for letting me know.  The next update fixes that issue.

## :large_blue_diamond: Install

Type in the following to the command line to install the dependency.

```bash
$ npm install --save react-native-gallery-swiper@latest
```

or

```bash
$ yarn add react-native-gallery-swiper@latest
```

**Comment by Luehang** [comment]
If you like `react-native-gallery-swiper`, be sure to give it a star!  Thanks.
