### ISSUE TITLE
Missing copyright statement

### ISSUE THREAD

**Issue by wooorm** [Luehang/react-native-gallery-swiper#54]
Furthering from https://github.com/Luehang/react-native-gallery-swiper/pull/44. Your statement here is [incorrect](https://github.com/Luehang/react-native-gallery-swiper/pull/44#issuecomment-625402641):

> These are free software and I don't know what your deal is. Legally, these are MIT and ISC licensed and free to use.

Your actions are illegal. You *must* credit the original work according to the ISC license. It is a mistake that the original work that you based your derivative work on does not include an explicit LICENSE file, however, that does not allow you to omit a copyright statement.

Something like:

```patch
MIT License

Copyright (c) 2018 Lue Hang
+Copyright (c) 2016 Archriss

Permission is hereby granted, free of charge, to any person obtaining a copy
```

And you *should* add a note to the readme, though that is not required.

**Comment by Luehang** [comment]
You don't know how ridiculous you sound right now.  Those previous repository don't even have that.

**Comment by Luehang** [comment]
`react-native-image-gallery` is suppose to have this. 

<br/>

```
Copyright (c) <date> ldn0x7dc 
```
