### ISSUE TITLE
Include credit to original library

### ISSUE THREAD

**Issue by romanonthego** [Luehang/react-native-gallery-swiper#55]
https://github.com/archriss/react-native-image-gallery indeed does not have `LICENSE` file, but `ISC` license type is explicitly stated in https://github.com/archriss/react-native-image-gallery/blob/master/package.json#L14
By very definition `ISC` requires copyright notice:
```
Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.
```

**Comment by Luehang** [comment]
Does not have license of original.

**Comment by Luehang** [comment]
"Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies."

**Comment by Luehang** [comment]
The whole time, maintainers are not putting down.

```
Copyright (c) <date> ldn0x7dc 
```
