### ISSUE TITLE
Credit the original author

### ISSUE THREAD

**Issue by griffinmartin** [Luehang/react-native-gallery-swiper#58]
@Luehang has ripped this project from https://github.com/archriss/react-native-image-gallery and claimed it as his own. Issues related to this are being closed.

[Explanation on Twitter 🍿](https://twitter.com/satya164/status/1277988371579707392)

See:
#44
#54
#55 
#56 
#57

**Comment by tweedge** [comment]
It was in the original README too as pointed out by [@killiman](https://twitter.com/kiliman/status/1278035675431010305) 

https://github.com/Luehang/react-native-gallery-swiper/commit/6705f094f7bc510ff4a166514b5477ae742e2ff1?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

"Improved and changed on top of `react-native-image-gallery.`"

**Comment by Luehang** [comment]
Not original.  And this software package is no longer maintained.
