### ISSUE TITLE
initialPage higher than 5 make the component freeze

### ISSUE THREAD

**Issue by alainib** [Luehang/react-native-gallery-swiper#7]
On android (not tested yet on ios) there is a bug when initialPage is used

	<GallerySwiper
           style={{ flex: 1, backgroundColor: Config.colors.background }}
           images={this.state.images}
           sensitiveScroll={false}
           onPageSelected={this.onChangeImage}
           initialPage={this.props.initialPage}
        />

- _if this.props.initialPage < 4 it work good
-  if this.props.initialPage == 5 the scroll work but image displayed is number 4
- _if this.props.initialPage > 5_  display image number 4 but no more swipe to left or right

PS: i get the same error with version of react-native-image-gallery higher than 2.1.4 ( with initialpage > 12

**Comment by Luehang** [comment]
Hi,

To solve this issue, change the `initialNumToRender` to match the initial page.

**Comment by alainib** [comment]
hello

thank's for the tips.
my `initialPage` can be very big like 200-300 , so init `initialNumToRender` with it make the component freeze

**Comment by Luehang** [comment]
Unfortunately, it does not support large numbers in `initialPage`, but it is performant and efficient for rendering large lists ranging from hundreds to thousands.

**Comment by ibu2710** [comment]
@alainib  Have you fixed this issue. Or how you managed this scenario. I am struggling with this. Please do suggest me a solution

**Comment by alainib** [comment]
> 
> 
> @alainib Have you fixed this issue. Or how you managed this scenario. I am struggling with this. Please do suggest me a solution

i don't use this package anymore 

i copied source code of https://github.com/archriss/react-native-image-gallery   V 2.1.4  and edited it (wrong import of PropTypes , should be `import PropTypes from "prop-types";` )
there is the same bug in version v 2.1.5  so i stick to 2.1.4 ( don't checked if there is higher and working version )

**Comment by ibu2710** [comment]
Thank you for your kind information.  Could you able to send me that File which you had edited?

mohamedibrahim2710@gmail.com

**Comment by Luehang** [comment]
https://github.com/Luehang/react-native-smart-gallery  In the open source development community, there isn't a single React Native gallery that can efficiently render a very large list of images with the initial index being placed anywhere in the list of images while supporting both Android and iOS. This gallery solves all that along with gestures and important event listeners for pan, pinch, single tap and double tap.

**Comment by fattomhk** [comment]
For anyone getting this issue, you might consider using initialScrollIndex if you do not want to render the images before.
