### ISSUE TITLE
[FEATURE REQUEST] onSwipeDown event

### ISSUE THREAD

**Issue by james1888** [Luehang/react-native-gallery-swiper#8]

**Comment by asasouza** [comment]
Hi @james1888 , you can use the `onTransformGestureReleased` prop to make an SwipeDown-like event. You can pass a function that receives the a `translate` object, observe the translateY value to fire the action that you want. For example:

`
	_handleTransform = (transform) => {
		const { scale, translateX: x, translateY: y } = transform;
		if (scale === 1 && (y < -90 || y > 90)) { // check if the image has no zoom (scale === 1) and if the user swiped up ou down the picture.
			this.setState({ visible: false });
		}
	}
`
The -90/90 value is the threshold that worked for me an especific case, you can use other value.

**Comment by suretarget** [comment]
Hi @asasouza, I try implement as you suggested but I don't know how to get a translate object. Can you show me an example. Thanks.

**Comment by asasouza** [comment]
Hello @suretarget, here is a simpler version of the  code I wrote to use the react-native-gallery-swiper as a component with custom functions in many places of my app. I hope this can solve your problem.
```
// Modules
import React, { PureComponent } from 'react';
import GallerySwiper from 'react-native-gallery-swiper';

class Gallery extends PureComponent {
	constructor(props) {
		super(props);

		this._handleTransform = this._handleTransform.bind(this);
	}

	_handleTransform(transform) {
		const { scale, translateY: y } = transform;
		if (scale === 1 && (y < -90 || y > 90)) {
			// here you place your custom swipe up/down behavior
			// My component is used inside a modal, so in this moment I call a function
			// to close the modal
			this.props.onDismiss();
		}
	}

	render() {
		const { initialPhoto, photos } = this.props;

		return (
			<GallerySwiper 
				images={photos}
				initialPage={initialPhoto}
				initialNumToRender={initialPhoto + 1}
				sensitiveScroll={false}
				onTransformGestureReleased={this._handleTransform}
				sensitiveScroll={false}
				removeClippedSubviews
			/>
		);
	}
}

export default Gallery;

```

**Comment by suretarget** [comment]
Thank you @asasouza

**Comment by infostreams** [comment]
Awesome, thank you so much! I think this should be either 

a) default behavior ('swipe to close' is sooooooo common) 
or 
b) in the README documentation

Nevertheless, great job, and many thanks for this nice library @Luehang - even though you should really really credit https://github.com/archriss/react-native-image-gallery because it seems you have quite a... ehm... overlap in code. At least acknowledge it.
